"""The estate's naming and numbering conventions.

Two sources of truth disagree here, deliberately:

* The **rules** are what the user told us, and are what new ports must follow.
* The **fixtures** are older than the rules. Legacy objects that do not follow them are not
  errors — they are history. Every function below therefore comes in a `for_new_*` flavour
  (what we generate) and a `classify_*`/`is_legacy_*` flavour (what we tolerate on audit).

Confusing those two is how a tool ends up reporting 300 switches as non-compliant.
"""

from __future__ import annotations

import ipaddress
import re
from dataclasses import dataclass

from .model import Environment

# --- I-SID numbering ---------------------------------------------------------------
#
# `<prefix><vlan zero-padded to 4>`. The prefix encodes the environment. Within an
# environment the two variants are, in the user's words, "the engineer's mood" -- both are
# valid, and we canonicalise on the lower one when generating.

ISID_PREFIX_CANONICAL: dict[Environment, int] = {
    Environment.PROD: 250,
    Environment.NONPROD: 270,
    Environment.SPECIAL: 299,
}

ISID_PREFIX_ACCEPTED: dict[int, Environment] = {
    250: Environment.PROD,
    251: Environment.PROD,
    270: Environment.NONPROD,
    271: Environment.NONPROD,
    299: Environment.SPECIAL,
}

#: Prefixes seen in the field that belong to neither scheme. 1531100 on the vIST VLAN is the
#: known example: infrastructure I-SIDs follow their own rules and we never generate them.
KNOWN_INFRA_PREFIXES: set[int] = {153}

MIN_VLAN_ID = 2
MAX_VLAN_ID = 4084

#: VLAN 31 is the reserved inter-switch trunk VLAN, estate-wide. Never allocate, never touch.
RESERVED_VLAN_IDS: set[int] = {1, 31}


class ConventionError(ValueError):
    """The requested value cannot be expressed under the estate's conventions."""


def isid_for_new_service(vlan_id: int, environment: Environment) -> int:
    """The I-SID a *new* service on `vlan_id` must use.

    >>> isid_for_new_service(695, Environment.PROD)
    2500695
    >>> isid_for_new_service(2200, Environment.NONPROD)
    2702200
    """
    if environment not in ISID_PREFIX_CANONICAL:
        raise ConventionError(
            f"no I-SID prefix is defined for environment {environment.value!r}; "
            "infrastructure I-SIDs are never generated by this tool"
        )
    if not MIN_VLAN_ID <= vlan_id <= MAX_VLAN_ID:
        raise ConventionError(f"VLAN {vlan_id} is outside the usable range {MIN_VLAN_ID}-{MAX_VLAN_ID}")
    if vlan_id in RESERVED_VLAN_IDS:
        raise ConventionError(f"VLAN {vlan_id} is reserved estate-wide and must not be used for a service")
    return int(f"{ISID_PREFIX_CANONICAL[environment]}{vlan_id:04d}")


@dataclass(frozen=True)
class IsidClassification:
    i_sid: int
    prefix: int
    environment: Environment | None
    vlan_id: int | None
    canonical: bool
    note: str | None = None


def classify_isid(i_sid: int) -> IsidClassification:
    """Decompose an existing I-SID. Tolerant: unknown shapes are described, not rejected."""
    text = str(i_sid)
    if len(text) != 7:
        return IsidClassification(i_sid, 0, None, None, False, f"not 7 digits, cannot decompose ({text})")
    prefix, tail = int(text[:3]), int(text[3:])
    if prefix in KNOWN_INFRA_PREFIXES:
        return IsidClassification(
            i_sid, prefix, Environment.INFRA, None, False,
            "known infrastructure prefix; follows its own scheme",
        )
    environment = ISID_PREFIX_ACCEPTED.get(prefix)
    if environment is None:
        return IsidClassification(i_sid, prefix, None, tail, False, f"unrecognised prefix {prefix}")
    canonical = prefix == ISID_PREFIX_CANONICAL[environment]
    note = None if canonical else f"legacy variant of the {environment.value} prefix (canonical is {ISID_PREFIX_CANONICAL[environment]})"
    return IsidClassification(i_sid, prefix, environment, tail, canonical, note)


def isid_matches_vlan(i_sid: int, vlan_id: int) -> bool:
    """True if `i_sid` encodes `vlan_id` under any accepted prefix."""
    decoded = classify_isid(i_sid)
    return decoded.vlan_id == vlan_id and decoded.environment in ISID_PREFIX_CANONICAL


# --- VLAN naming -------------------------------------------------------------------
#
# `<LETTER><12 digits><_prefixlen>`, where the digits are the four octets of the network
# address zero-padded to three each. `E010035016000_21` == 10.35.16.0/21.
#
# The meaning of the leading letter is UNKNOWN -- the user does not know it either. So we
# decode and verify names, and we never invent a letter: generating a name requires the
# caller to supply one (from a profile), and audit only reports a mismatch between the name
# and the subnet it claims.

VLAN_NAME_RE = re.compile(r"^(?P<letter>[A-Za-z])(?P<digits>\d{12})_(?P<prefixlen>\d{1,2})$")


@dataclass(frozen=True)
class DecodedVlanName:
    letter: str
    network: ipaddress.IPv4Network
    raw: str


def decode_vlan_name(name: str) -> DecodedVlanName | None:
    """Decode a conventional VLAN name, or None if it does not follow the scheme.

    >>> decode_vlan_name("E010035016000_21").network
    IPv4Network('10.35.16.0/21')
    >>> decode_vlan_name("quarantine") is None
    True
    """
    match = VLAN_NAME_RE.match(name.strip())
    if match is None:
        return None
    digits = match["digits"]
    octets = [int(digits[i : i + 3]) for i in range(0, 12, 3)]
    if any(o > 255 for o in octets):
        return None
    try:
        network = ipaddress.IPv4Network(
            f"{'.'.join(str(o) for o in octets)}/{int(match['prefixlen'])}", strict=False
        )
    except ValueError:
        return None
    return DecodedVlanName(letter=match["letter"], network=network, raw=name.strip())


def encode_vlan_name(network: ipaddress.IPv4Network | str, letter: str) -> str:
    """Build a conventional VLAN name. `letter` must be supplied -- we do not guess it.

    >>> encode_vlan_name("10.35.16.0/21", "E")
    'E010035016000_21'
    """
    net = ipaddress.IPv4Network(network, strict=False)
    if len(letter) != 1 or not letter.isalpha():
        raise ConventionError(f"VLAN-name letter must be a single letter, got {letter!r}")
    digits = "".join(f"{int(o):03d}" for o in str(net.network_address).split("."))
    return f"{letter.upper()}{digits}_{net.prefixlen}"


def vlan_name_is_consistent(name: str, network: ipaddress.IPv4Network | str) -> bool:
    """True if a conventional name describes `network`. False for both a mismatch and a
    name that does not follow the scheme -- callers distinguish via `decode_vlan_name`."""
    decoded = decode_vlan_name(name)
    if decoded is None:
        return False
    return decoded.network == ipaddress.IPv4Network(network, strict=False)


# --- MLT numbering -----------------------------------------------------------------
#
# The rule for NEW MLTs: 4xx, where xx is the port number. Port 1/10 -> MLT 410.
# The fixtures show legacy ids (196-200) that predate it; `is_legacy_mlt_id` exists so audit
# can say "legacy" rather than "wrong".

MLT_NEW_BASE = 400
MLT_ID_MAX = 512


def mlt_id_for_new_lag(port_id: str) -> int:
    """MLT id for a new LAG whose member port is `port_id`.

    >>> mlt_id_for_new_lag("1/10")
    410
    >>> mlt_id_for_new_lag("1/43")
    443
    """
    parts = port_id.strip().split("/")
    if len(parts) != 2:
        # Channelized sub-ports (2/1/1) have no defined rule. Open question for the user.
        raise ConventionError(
            f"the 4xx MLT convention is only defined for slot/port ids; {port_id!r} has "
            f"{len(parts)} parts and needs an explicit MLT id"
        )
    try:
        port_number = int(parts[1])
    except ValueError as exc:
        raise ConventionError(f"cannot read a port number out of {port_id!r}") from exc
    if not 1 <= port_number <= 99:
        raise ConventionError(
            f"the 4xx convention only encodes ports 1-99; port {port_number} needs an explicit MLT id"
        )
    return MLT_NEW_BASE + port_number


def mlt_id_matches_port(mlt_id: int, port_id: str) -> bool:
    """True if `mlt_id` follows the 4xx convention for `port_id`."""
    try:
        return mlt_id_for_new_lag(port_id) == mlt_id
    except ConventionError:
        return False


def is_legacy_mlt_id(mlt_id: int) -> bool:
    """An id outside the 4xx block, i.e. one that predates the convention."""
    return not (MLT_NEW_BASE < mlt_id <= MLT_NEW_BASE + 99)


def lacp_key_for(mlt_id: int) -> int:
    """LACP key equals the MLT id. Verified in real running-config (`mlt 197` / `key 197`)."""
    return mlt_id
